security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            pattern: ^/(.*)
            form_login:
                enable_csrf: true
                login_path: dcms_login
                check_path: dcms_login
                password_parameter: password
                post_only: true
                csrf_token_id: 'auth'
            logout:
                path: dcms_logout
    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }